# NIFTY 50 Stocks (as of 2024)
nifty50:
  - "RELIANCE.NS"
  - "TCS.NS"
  - "HDFCBANK.NS"
  - "INFY.NS"
  - "ICICIBANK.NS"
  - "HINDUNILVR.NS"
  - "ITC.NS"
  - "SBIN.NS"
  - "BHARTIARTL.NS"
  - "KOTAKBANK.NS"
  - "BAJFINANCE.NS"
  - "LT.NS"
  - "ASIANPAINT.NS"
  - "AXISBANK.NS"
  - "MARUTI.NS"
  - "SUNPHARMA.NS"
  - "TITAN.NS"
  - "ULTRACEMCO.NS"
  - "NESTLEIND.NS"
  - "WIPRO.NS"
  - "HCLTECH.NS"
  - "ADANIENT.NS"
  - "ONGC.NS"
  - "NTPC.NS"
  - "POWERGRID.NS"
  - "M&M.NS"
  - "JSWSTEEL.NS"
  - "TATAMOTORS.NS"
  - "TECHM.NS"
  - "INDUSINDBK.NS"
  - "BAJAJFINSV.NS"
  - "TATASTEEL.NS"
  - "HINDALCO.NS"
  - "COALINDIA.NS"
  - "ADANIPORTS.NS"
  - "DIVISLAB.NS"
  - "DRREDDY.NS"
  - "CIPLA.NS"
  - "EICHERMOT.NS"
  - "HEROMOTOCO.NS"
  - "BRITANNIA.NS"
  - "APOLLOHOSP.NS"
  - "GRASIM.NS"
  - "BPCL.NS"
  - "TATACONSUM.NS"
  - "UPL.NS"
  - "BAJAJ-AUTO.NS"
  - "SBILIFE.NS"
  - "LTIM.NS"
  - "HDFCLIFE.NS"

# Popular Mid-Cap stocks
midcap:
  - "GODREJCP.NS"
  - "PIIND.NS"
  - "SIEMENS.NS"
  - "BOSCHLTD.NS"
  - "HAVELLS.NS"
  - "BERGEPAINT.NS"
  - "PIDILITIND.NS"
  - "MPHASIS.NS"
  - "MINDTREE.NS"
  - "PERSISTENT.NS"

# Indices
indices:
  - "^NSEI"      # NIFTY 50
  - "^NSEBANK"   # BANK NIFTY
  - "^CNXIT"     # NIFTY IT
  - "^CNXAUTO"   # NIFTY AUTO
  - "^CNXPHARMA" # NIFTY PHARMA

